// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Synthbot.DAL;

namespace Synthbot.WebApp.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
    [Migration("20180916213148_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("SynthbotUserId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("SynthbotUserId");

                    b.HasIndex("UserId");

                    b.ToTable("SynthbotUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("SynthbotUserId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("SynthbotUserId");

                    b.HasIndex("UserId");

                    b.ToTable("SynthbotUserLoginProviders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("SynthbotUserId");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("SynthbotUserId");

                    b.ToTable("SynthbotUserTokens");
                });

            modelBuilder.Entity("Synthbot.WebApp.Models.ReferralTokenReceipt", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Claimed");

                    b.Property<DateTime>("ClaimedTS");

                    b.Property<DateTime>("ReceivedTS");

                    b.Property<string>("ReferralUserId");

                    b.Property<string>("ReferrerSignalrUser");

                    b.Property<bool>("ReplyError");

                    b.Property<bool>("ReplySent");

                    b.Property<string>("SynthbotUserId");

                    b.HasKey("Id");

                    b.HasIndex("SynthbotUserId");

                    b.ToTable("ReferralTokenReceipts");
                });

            modelBuilder.Entity("Synthbot.WebApp.Models.SynthbotUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("DiscordEmailAddress");

                    b.Property<string>("DiscordUserId");

                    b.Property<string>("DiscordUsername");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("SynthbotUsers");
                });

            modelBuilder.Entity("Synthbot.WebApp.Models.VoiceChannelActivePlaylist", b =>
                {
                    b.Property<string>("DiscordVoiceChannelId");

                    b.Property<string>("SpotifyPlaylistId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("DiscordVoiceChannelId", "SpotifyPlaylistId");

                    b.HasIndex("DiscordVoiceChannelId")
                        .IsUnique();

                    b.HasIndex("SpotifyPlaylistId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("VoiceChannelActivePlaylists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser")
                        .WithMany("UserClaims")
                        .HasForeignKey("SynthbotUserId");

                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser")
                        .WithMany("UserLogins")
                        .HasForeignKey("SynthbotUserId");

                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser")
                        .WithMany("UserTokens")
                        .HasForeignKey("SynthbotUserId");

                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Synthbot.WebApp.Models.ReferralTokenReceipt", b =>
                {
                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser", "SynthbotUser")
                        .WithMany()
                        .HasForeignKey("SynthbotUserId");
                });

            modelBuilder.Entity("Synthbot.WebApp.Models.VoiceChannelActivePlaylist", b =>
                {
                    b.HasOne("Synthbot.WebApp.Models.SynthbotUser", "User")
                        .WithMany("OwnerActivePlaylists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
